INFO     HTTP_CLIENT:event_hooks.py:25 Make POST request to http://localhost:8000/api/v1/users
INFO     HTTP_CLIENT:event_hooks.py:34 Got response 200 OK from http://localhost:8000/api/v1/users
INFO     HTTP_CLIENT:event_hooks.py:25 Make POST request to http://localhost:8000/api/v1/authentication/login
INFO     HTTP_CLIENT:event_hooks.py:34 Got response 200 OK from http://localhost:8000/api/v1/authentication/login
INFO     HTTP_CLIENT:event_hooks.py:25 Make GET request to http://localhost:8000/api/v1/files/incorrect_file_id
INFO     HTTP_CLIENT:event_hooks.py:34 Got response 422 Unprocessable Entity from http://localhost:8000/api/v1/files/incorrect_file_id
INFO     BASE_ASSERTIONS:base.py:19 Check that response status code equals to '422'
INFO     FILES_ASSERTIONS:files.py:147 Check get file with incorrect file id response
INFO     ERRORS_ASSERTIONS:errors.py:40 Check validation error response
INFO     BASE_ASSERTIONS:base.py:69 Check that length of 'details' equals to '1'
INFO     ERRORS_ASSERTIONS:errors.py:21 Check validation error
INFO     BASE_ASSERTIONS:base.py:37 Check that 'type' equals to 'uuid_parsing'
INFO     BASE_ASSERTIONS:base.py:37 Check that 'input' equals to 'incorrect_file_id'
INFO     BASE_ASSERTIONS:base.py:37 Check that 'context' equals to '{'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}'
INFO     BASE_ASSERTIONS:base.py:37 Check that 'message' equals to 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'
INFO     BASE_ASSERTIONS:base.py:69 Check that length of 'location' equals to '2'
INFO     SCHEMA_ASSERTIONS:schema.py:21 Validate JSON schema